# Russian UI string -> (English, Swedish). Terms match the article translations.
G = {
# ---- titles / sections
"Настройки": ("Settings","Inställningar"),
"Настройки EV3": ("EV3 Settings","EV3-inställningar"),
"Настройки приложения": ("App settings","Appinställningar"),
"Настройки сервера": ("Server settings","Serverinställningar"),
"Сервер": ("Server","Server"),
"Робот": ("Robot","Robot"),
"Список настроек роботов": ("List of robot settings","Lista över robotinställningar"),
"Текущие настройки робота": ("Current robot settings","Aktuella robotinställningar"),
"Импорт настроек робота": ("Import robot settings","Importera robotinställningar"),
"Нестандартный робот": ("Non-standard robot","Icke-standardrobot"),
"Общая информация": ("General information","Allmän information"),
"Безопасность": ("Security","Säkerhet"),
"Камера": ("Camera","Kamera"),
"Тыловая": ("Rear","Bakre"),
"Размер изображения": ("Image size","Bildstorlek"),
"Качество JPEG": ("JPEG quality","JPEG-kvalitet"),
"Имя водителя": ("Driver name","Förarens namn"),
"Пароль водителя": ("Driver password","Förarens lösenord"),
"Разрешить наблюдателей": ("Allow observers","Tillåt observatörer"),
"Имя наблюдателя": ("Observer name","Observatörens namn"),
"Пароль наблюдателя": ("Observer password","Observatörens lösenord"),
"Использовать локальные": ("Use local","Använd lokala"),
"элементы управления": ("controls","reglage"),
"Максимально увеличить": ("Maximise","Maximera"),
"джойстики": ("joysticks","styrspakar"),
# ---- buttons
"ОТМЕНА": ("CANCEL","AVBRYT"),
"СОХРАНИТЬ": ("SAVE","SPARA"),
"УДАЛИТЬ": ("DELETE","TA BORT"),
"ДОБАВИТЬ": ("ADD","LÄGG TILL"),
"РАЗРЕШИТЬ": ("ALLOW","TILLÅT"),
"ОТКЛОНИТЬ": ("DENY","NEKA"),
"Отмена": ("Cancel","Avbryt"),
"Сохранить": ("Save","Spara"),
"Отмена|Сохранить": ("Cancel|Save","Avbryt|Spara"),
"Удалить": ("Delete","Ta bort"),
"Добавить": ("Add","Lägg till"),
"Удалить|Добавить": ("Delete|Add","Ta bort|Lägg till"),
"Да": ("Yes","Ja"),
"Нет|Да": ("No|Yes","Nej|Ja"),
"готово": ("done","klar"),
"ГОТОВО": ("DONE","KLAR"),
"Разрешить": ("Allow","Tillåt"),
"Больше не запрашивать": ("Don't ask again","Fråga inte igen"),
"Отправить": ("Send","Skicka"),
"Сделать копию": ("Make a copy","Skapa kopia"),
"Экспортировать в файл": ("Export to file","Exportera till fil"),
"Импортировать из файла": ("Import from file","Importera från fil"),
"Войти": ("Log in","Logga in"),
# ---- robot settings
"Название робота": ("Robot name","Robotens namn"),
"Описание": ("Description","Beskrivning"),
"Исследователь EV3": ("EV3 Explorer","EV3 Explorer"),
"Джойстик 1": ("Joystick 1","Styrspak 1"),
"Джойстик 2": ("Joystick 2","Styrspak 2"),
"Джойстик 3": ("Joystick 3","Styrspak 3"),
"Джойстик 4": ("Joystick 4","Styrspak 4"),
"Видимость": ("Visibility","Synlighet"),
"Форма": ("Shape","Form"),
"Круглая": ("Round","Rund"),
"Тип": ("Type","Typ"),
"Руление 1 (может двигаться как машина)": ("Steering 1 (can drive like a car)","Styrning 1 (kan köra som en bil)"),
"Руление": ("Steering","Styrning"),
"Независимые моторы": ("Independent motors","Oberoende motorer"),
"Почтовый ящик": ("Mailbox","Brevlåda"),
"Окончание прикосновения": ("End of touch","Slut på beröring"),
"(для горизонтальной оси)": ("(for horizontal axis)","(för horisontell axel)"),
"(для вертикальной оси)": ("(for vertical axis)","(för vertikal axel)"),
"Возвращаться к нулю": ("Return to zero","Återgå till noll"),
"Сохранять позицию": ("Keep position","Behåll position"),
"Вертикальная": ("Vertical","Vertikal"),
"Левый": ("Left","Vänster"),
"Мотор": ("Motor","Motor"),
"Модуль EV3": ("EV3 brick","EV3-enhet"),
"Номер порта": ("Port number","Portnummer"),
"Ось джойстика": ("Joystick axis","Styrspakens axel"),
"Изменяемое значение": ("Changed value","Ändrat värde"),
"Угол поворота мотора": ("Motor rotation angle","Motorns vridningsvinkel"),
"Мощность": ("Power","Effekt"),
"Инвертировать": ("Invert","Invertera"),
"Тормозить": ("Brake","Bromsa"),
"Коэффициент": ("Coefficient","Koefficient"),
"Порты джойстика 1": ("Joystick 1 ports","Styrspak 1 portar"),
"Порты джойстика 2": ("Joystick 2 ports","Styrspak 2 portar"),
"Порты группы клавиш 1": ("Key group 1 ports","Tangentgrupp 1 portar"),
"Джойстик 1 порт В": ("Joystick 1 port B","Styrspak 1 port B"),
"Джойстик 1 порт C": ("Joystick 1 port C","Styrspak 1 port C"),
"Джойстик 2 порт А": ("Joystick 2 port A","Styrspak 2 port A"),
"Группа клавиш 1 порт В": ("Key group 1 port B","Tangentgrupp 1 port B"),
"Показывать отладочную": ("Show debug","Visa felsöknings-"),
"информацию": ("information","information"),
"Скрывать джойстики при": ("Hide joysticks when","Dölj styrspakar vid"),
"использовании клавиатуры": ("using the keyboard","tangentbordsanvändning"),
"Запускать программу": ("Run program","Kör program"),
"Простой колёсный робот с упр": ("A simple wheeled robot with controllable phone holder","En enkel hjulrobot med styrbar telefonhållare"),
"EV3: Простой колёсный робот с управляемым": ("EV3: A simple wheeled robot with a","EV3: En enkel hjulrobot med en"),
"держателем смартфона.": ("controllable phone holder.","styrbar telefonhållare."),
"EV3: Гоночная машина Формула 1 (обычная": ("EV3: Formula 1 racing car (regular","EV3: Racerbil Formel 1 (vanlig"),
"EV3: Гоночная машина формула 1 (скоростная": ("EV3: Formula 1 racing car (speed","EV3: Racerbil Formel 1 (snabb"),
"версия)": ("version)","version)"),
"Гоночная машина скоростн.": ("Racing car, speed","Racerbil, snabb"),
"Гоночная машина станд.": ("Racing car, standard","Racerbil, standard"),
"EV3: Может хватать и приподнимать предметы": ("EV3: Can grab and lift objects","EV3: Kan gripa och lyfta föremål"),
"EV3: Шагающий луноход": ("EV3: Walking lunar rover","EV3: Gående månbil"),
"Селеноход EV3": ("Selenokhod EV3","Selenokhod EV3"),
"Робот с клешнёй": ("Claw robot","Klorobot"),
"Нестанд.: Arduino researcher": ("Non-std.: Arduino researcher","Icke-std.: Arduino researcher"),
"Позывной/Ответ": ("Callsign/Reply","Anropssignal/Svar"),
"Позывной": ("Callsign","Anropssignal"),
"Ответ": ("Reply","Svar"),
# ---- keys
"Группы клавиш": ("Key groups","Tangentgrupper"),
"Группа клавиш 1": ("Key group 1","Tangentgrupp 1"),
"Группа клавиш 2": ("Key group 2","Tangentgrupp 2"),
"Активность": ("Active","Aktiv"),
"АКТИВНОСТЬ": ("ACTIVE","AKTIV"),
"Клавиши": ("Keys","Tangenter"),
"Клавиши вверх": ("Up keys","Upp-tangenter"),
"Клавиши влево": ("Left keys","Vänster-tangenter"),
"Клавиши вниз": ("Down keys","Ner-tangenter"),
"Клавиши вправо": ("Right keys","Höger-tangenter"),
"Выбрано: W, Up": ("Selected: W, Up","Valda: W, Up"),
"Ничего не выбрано": ("Nothing selected","Inget valt"),
"Название почтового ящика": ("Mailbox name","Brevlådenamn"),
"Окончание нажатия (для": ("End of press (for","Slut på tryckning (för"),
"клавиш влево/вправо)": ("left/right keys)","vänster/höger-tangenter)"),
"клавиш вверх/вниз)": ("up/down keys)","upp/ner-tangenter)"),
"Увеличение по горизонтали": ("Increase horizontally","Ökning horisontellt"),
"Увеличение по вертикали": ("Increase vertically","Ökning vertikalt"),
"Уменьшение по горизонтали": ("Decrease horizontally","Minskning horisontellt"),
"Уменьшение по вертикали": ("Decrease vertically","Minskning vertikalt"),
"Значение изменяющее мощность и угол за": ("Value that changes power and angle per","Värde som ändrar effekt och vinkel per"),
"единицу времени. Допустимые значения 0-200": ("unit of time. Allowed values 0-200","tidsenhet. Tillåtna värden 0-200"),
"Пауза между": ("Pause between","Paus mellan"),
"Пауза между вертикальными": ("Pause between vertical","Paus mellan vertikala"),
"горизонтальными": ("horizontal","horisontella"),
"увеличениями/уменьшениями": ("increases/decreases","ökningar/minskningar"),
# ---- dialogs / Android
"Запрос на разрешение": ("Bluetooth connection","Begäran om tillstånd"),
"подключения Bluetooth": ("permission request","för Bluetooth-anslutning"),
"Приложение запрашивает": ("The app is requesting","Appen begär tillstånd"),
"разрешение на включение": ("permission to turn on","att slå på"),
"Bluetooth. Разрешить?": ("Bluetooth. Allow?","Bluetooth. Tillåta?"),
"приложению": ("the app","appen"),
"доступ к камере для": ("access to the camera for","åtkomst till kameran för"),
"фото- и видеосъемки?": ("photo and video capture?","foto och videoinspelning?"),
"к фото, медиа и": ("to photos, media and","till foton, media och"),
"файлам на вашем": ("files on your","filer på din"),
"устройстве?": ("device?","enhet?"),
"Выполнить действие с": ("Complete action","Slutför åtgärd"),
"помощью": ("using","med"),
"Всегда": ("Always","Alltid"),
"Только один раз": ("Just once","Bara en gång"),
"ВКонтакте": ("VKontakte","VKontakte"),
"Яндекс.Карты": ("Yandex Maps","Yandex Kartor"),
"Настройки успешно": ("Settings successfully","Inställningarna har"),
"Файл": ("File","Arkiv"),
"Редактировать": ("Edit","Redigera"),
"Инструменты": ("Tools","Verktyg"),
"Справка": ("Help","Hjälp"),

# ---- status labels on the camera view
"Начать управление...": ("Start control...","Starta styrning..."),
"Сервер RoboCam работает": ("RoboCam server is running","RoboCam-servern körs"),
"Сервер RoboCam выключен": ("RoboCam server is off","RoboCam-servern är avstängd"),
"EV3 не подключен:": ("EV3 not connected:","EV3 inte ansluten:"),
"Подключено к EV3:": ("Connected to EV3:","Ansluten till EV3:"),
"Робот не подключен:": ("Robot not connected:","Roboten inte ansluten:"),
'"RoboCam" доступ': ('"RoboCam" access','"RoboCam" åtkomst'),
'"RoboCam" Прямой': ('"RoboCam" direct','"RoboCam" direkt'),
"Окончание": ("End of","Slut på"),
"Сервер RoboCam работает:": ("RoboCam server is running:","RoboCam-servern körs:"),
"Настройки успешно импортированы": ("Settings imported successfully","Inställningarna importerades"),
"Исследователь EV3 2": ("EV3 Explorer 2","EV3 Explorer 2"),
"экспортированы в файл /": ("exported to file /","exporterats till fil /"),
"Программное обеспечение для учителя": ("Software for teachers","Programvara för lärare"),
}
